### ISSUE TITLE
mifish crashes when a group has been skipped

### ISSUE THREAD

**Issue by cement-head** [billzt/MiFish#9]
I am using three groups; this sample <Sample 21_Pt4_LO_S_1_> in the first group has only 27 reads and is **skipped** during initial processing.

```
Sample 21_Pt4_LO_S_1_ Step 0: Decompress
Sample 21_Pt4_LO_S_1_ Step 1: filter the quality of FASTQ and merge Pair-End Reads
Sample 21_Pt4_LO_S_1_ Step 2: filter read length and remove primers
Sample 21_Pt4_LO_S_1_ has not passed read length filter. Only has 27 reads. Skip
```

Later, the pipeline crashes:

```
Traceback (most recent call last):
  File "/home/cbfgws6/miniconda3/envs/MiFish/bin/mifish", line 33, in <module>
    sys.exit(load_entry_point('mifish', 'console_scripts', 'mifish')())
  File "/home/cbfgws6/MiFish/mifish/cmd/mifish.py", line 76, in main
    pipeline.runMiFish(data_dir=args.seq_dir, data_dir_other_groups=data_dir_other_groups, \
  File "/home/cbfgws6/MiFish/mifish/core/pipeline.py", line 397, in runMiFish
    json.dump(stat.eco_diversity(workdir, group_to_sample), fp=out_handle, indent=4)
  File "/home/cbfgws6/MiFish/mifish/core/stat.py", line 79, in eco_diversity
    with open(f'{workdir_sample}/04_blast/{sample_name}.json') as handle:
FileNotFoundError: [Errno 2] No such file or directory: 'output/WTRBA-YEARS/MiFishResult/Sample-21_Pt4_LO_S_1_/04_blast/21_Pt4_LO_S_1_.json'
```

It is true that there is no JSON file, as it was skipped.  The pipeline should figure this out, or at least not crash, and move on to the next sample.

The immediate workaround would be to remove this sample (or any samples that are "SKIPPED" from the analysis/pipeline.

**Comment by tao-bioinfo** [comment]
Sorry, please clone the latest repo and try again.

**Comment by cement-head** [comment]
@billzt I download (cloned) the repo on Sept 28th, 2023 - have their been updates since?

----------------------------------------

Nevermind, I see that there's been a patch - I'll try it now.

**Comment by cement-head** [comment]
okay  - works!  Thanks!
